modLoader="javafml"
loaderVersion="[3,]"
issueTrackerURL="https://github.com/BehindTheScenery/Argentum/issues"
logoFile="neoforged_logo.png"
license="LGPL v2.1"

[[mods]]
    modId="neoforge"
    # We use the global NeoForge version
    version="${global.neoForgeVersion}"
    displayURL = "https://github.com/BehindTheScenery/Argentum"
    displayName="Argentum"
    credits="Thanks to NeoForge for the possibility of forks"
    authors="Aros, BehindTheScenery"
    description='''
    Argentum, fork of NeoForge by BTS with native Vulkan support and much more
    '''

[[mixins]]
    config = "neoforge.mixins.json"
